### ISSUE TITLE
cv2.error (error: (-215:Assertion failed))

### ISSUE THREAD

**Issue by JonathanWillnow** [vncsms/Metin2FishBot#10]
Hey mate,

I tried this module for fun since and got the following error:

Traceback (most recent call last):
  File "hack.py", line 27, in <module>
  File "fishingbot.py", line 263, in runHack
  File "fishingbot.py", line 81, in detect
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1164: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'

[19352] Failed to execute script 'hack' due to unhandled exception!

I looked into the code and it seems these lines
` #match the needle_image with the hasytack image`
`result = cv.matchTemplate(haystack_img, self.needle_img, cv.TM_CCOEFF_NORMED)`

are the problem.

I have to say that I tried to install all the stuff from your requirements.txt, but I have problems with opencv-python==4.3.0.36.
I could not install this specific version:

ERROR: No matching distribution found for opencv-python==4.3.0.36

So I went with the newest one for which your project is not working. Maybe you have a way to get your verion of the package?

Best regards!

**Comment by JonathanWillnow** [comment]
Solved, my mistake
