### ISSUE TITLE
Bot crash as soon i start it.

### ISSUE THREAD

**Issue by hAlessio** [vncsms/Metin2FishBot#22]
Hi i'm trying to use this bot on WoM2 i did everything right i also changed the values of the minigame windows inside the .py files and also created the executable file after all these changes, the problem is that when i start the bot as soon the cursor goes into the game window it simply crash, i think that they patched it, there will be a new update for it or you're out of this project for now?

**Comment by hAlessio** [comment]
i managed to see the error that i get

Traceback (most recent call last):
  File "hack.py", line 27, in <module>
    fishbot.runHack()
  File "fishingbot.py", line 178, in runHack
    screenshot = self.wincap.get_screenshot()
                           ^^^^^^^^^^^^^^^^^
  File "windowcapture.py", line 47, in get__screenshot
     dataBitMap.CreateCompatibleBitmap(dcObj, self.w, self.h)
 win32ui.error: CreateCompatibleDC failed
 [15682] Failed to execute script 'hack' due to unhandled exception!

**Comment by hAlessio** [comment]
oops my bad, this is the error that i got becouse the m2 window wasn't on top, the real err is this
Traceback (most recent call last):
  File "hack.py", line 27 in <module>
     fishbot.runHack()
  File "fishingbot.py", line 181 in runHack
     crop_img = screenshot[self.FISH_WINDOW_POSITION[1]:self.FISH_WINDOW_POSITION[1]+self.FISH_WINDOW_SIZE[1],
                                                                                                                                ^^^^^^^^^^^^^^^^
AttributeError: 'FishingBot' object has no attribute 'FISH_WINDOW_SIZE' , Did you mean: 'FISH_WINDOW_CLOSE'?
[15940] Failed to execute script 'hack' due to unhandled exception!
