### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by qblaize** [vncsms/Metin2FishBot#5]
Hi, i followed the steps, but after i press start, it gives me this error:
Traceback (most recent call last):
  File "hack.py", line 27, in <module>
  File "fishingbot.py", line 235, in runHack
  File "fishingbot.py", line 137, in detect_minigame
cv2.error: OpenCV(4.3.0) C:\projects\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1104: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'

[16160] Failed to execute script hack

**Comment by vncsms** [comment]
Can you add me on discord: picicio#4827

**Comment by vncsms** [comment]
It was the version of python. 3.8 or higher is the ideal
